export const individualServices = [
  {
    name: "1 Automation Workflow",
    price: "£150",
    price_id: "price_1T4FYxC1I7VBCNgyEOGXmbH2",
    description: "A single custom automation workflow built for your business",
    icon: "Workflow",
  },
  {
    name: "AI Chatbot for Website",
    price: "£250",
    price_id: "price_1T4FZPC1I7VBCNgyuerLz6lb",
    description: "AI-powered chatbot for your website with custom training",
    icon: "Bot",
  },
  {
    name: "Email & Form Automation",
    price: "£100",
    price_id: "price_1T4FZfC1I7VBCNgymwFyhLGB",
    description: "Automated email responses and form processing",
    icon: "Mail",
  },
  {
    name: "Custom AI Agents",
    price: "£350",
    price_id: "price_1T4FaQC1I7VBCNgyFc88aR0R",
    description: "Custom AI agents tailored to your sales, support, or operations",
    icon: "Bot",
  },
  {
    name: "CRM & Pipeline Automation",
    price: "£200",
    price_id: "price_1T4FaoC1I7VBCNgyuf9gDWDK",
    description: "Automated CRM and sales pipeline management",
    icon: "Users",
  },
  {
    name: "Lead Scoring & Follow-ups",
    price: "£150",
    price_id: "price_1T4Fb6C1I7VBCNgyOZePGJvz",
    description: "Automated lead scoring and follow-up sequences",
    icon: "Target",
  },
  {
    name: "Full API Integrations",
    price: "£300",
    price_id: "price_1T4FbEC1I7VBCNgyDfuaNPZD",
    description: "Full API integrations with your existing tools and platforms",
    icon: "Plug",
  },
  {
    name: "Custom AI Development",
    price: "£500",
    price_id: "price_1T4FbJC1I7VBCNgykdqpPzQ6",
    description: "Bespoke AI development tailored to your business needs",
    icon: "Code2",
  },
  {
    name: "Team Training",
    price: "£200",
    price_id: "price_1T4FbOC1I7VBCNgyt8Mezt7U",
    description: "Comprehensive team training on AI automation tools",
    icon: "GraduationCap",
  },
  {
    name: "White-label Options",
    price: "£400",
    price_id: "price_1T4FbPC1I7VBCNgyQP04CEgS",
    description: "White-label AI automation solutions under your brand",
    icon: "Tag",
  },
] as const;
