export const individualServices = [
  {
    name: "1 Automation Workflow",
    price: "£297",
    price_id: "price_1UFrVHC1I7VBCNgy4DGV5C7q",
    description: "A single custom automation workflow built for your business",
    icon: "Workflow",
  },
  {
    name: "AI Chatbot for Website",
    price: "£497",
    price_id: "price_1UFrVPC1I7VBCNgysZz3XOvl",
    description: "AI-powered chatbot for your website with custom training",
    icon: "Bot",
  },
  {
    name: "Email & Form Automation",
    price: "£197",
    price_id: "price_1UFrVXC1I7VBCNgyF2TuIwRd",
    description: "Automated email responses and form processing",
    icon: "Mail",
  },
  {
    name: "Custom AI Agents",
    price: "£697",
    price_id: "price_1UFrViC1I7VBCNgy83bbs7KA",
    description: "Custom AI agents tailored to your sales, support, or operations",
    icon: "Bot",
  },
  {
    name: "CRM & Pipeline Automation",
    price: "£397",
    price_id: "price_1UFrW6C1I7VBCNgy1TeEIpR6",
    description: "Automated CRM and sales pipeline management",
    icon: "Users",
  },
  {
    name: "Lead Scoring & Follow-ups",
    price: "£297",
    price_id: "price_1UFrWXC1I7VBCNgyIGt7EYOM",
    description: "Automated lead scoring and follow-up sequences",
    icon: "Target",
  },
  {
    name: "Full API Integrations",
    price: "£597",
    price_id: "price_1UFrWzC1I7VBCNgySffUc72Z",
    description: "Full API integrations with your existing tools and platforms",
    icon: "Plug",
  },
  {
    name: "Custom AI Development",
    price: "£997",
    price_id: "price_1UFrXNC1I7VBCNgyTvDJN7YG",
    description: "Bespoke AI development tailored to your business needs",
    icon: "Code2",
  },
  {
    name: "Team Training",
    price: "£297",
    price_id: "price_1UFrXhC1I7VBCNgyDcCOHQhd",
    description: "Comprehensive team training on AI automation tools",
    icon: "GraduationCap",
  },
  {
    name: "White-label Options",
    price: "£400",
    price_id: "price_1T4FbPC1I7VBCNgyQP04CEgS",
    description: "White-label AI automation solutions under your brand",
    icon: "Tag",
  },
] as const;
